---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cargo
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cat '/etc/os-release'
          rustc -V
          set -xeuo pipefail
          sudo apt-get update
          sudo apt-get install -y cargo=1.74
          cargo build --quiet
          cargo clippy --quiet
          cargo test --quiet
          cargo fmt --check --all

